---
- name: Installation des serveurs web
  hosts: web
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Add deploy user
      user:
        name: deploy
        shell: /bin/bash

    - name: Add ssh key
      authorized_key:
        user: deploy
        key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"

    - name: Install Ruby dependencies
      apt:
        name: [
          'gcc',
          'autoconf',
          'bison',
          'build-essential',
          'libssl-dev',
          'libyaml-dev',
          'libreadline6-dev',
          'zlib1g-dev',
          'libncurses5-dev',
          'libffi-dev',
          'libgdbm3',
          'libgdbm-dev',
          'sqlite3',
          'libsqlite3-dev',
          'nodejs'
        ]
