---
- name: Install webservers
  hosts: web
  become: yes
  vars:
    project_path: /home/deploy/var/www/{{ inventory_hostname }}
  tasks:
    - name: Update and upgrade all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
  roles:
    - utils
    - user
    - ruby
    - postgres
    - postfix
    # - imagemagick
    # - node
    - { role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['{{ ruby_version }}'],
        rvm1_user: 'deploy'
      }
    - nginx


