---
- name: Install webservers
  hosts: web
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
  roles:
    - utils
    - user
    - ruby
    - postfix
    - imagemagick
    - node

    
