---
- name: Install webservers
  hosts: web
  become: yes
  vars:
    dist: bionic
    project_path: /home/deploy/www/{{ inventory_hostname }}
    env_vars:
      - key: "{{ secret_key_base_name }}"
        value : ce7aa3b7bce10b13e060653fa3b4fbc98a4a1558e31a3a674ad20256d5bdc7cab4583224b945228fbf5292f66b4cd049da1ea5daa526cb3338dace2762442c9e
    ssh_keys:
      - "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
  pre_tasks:
    - name: Update and upgrade all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
  roles:
    - utils
    - user
    - ruby
    - postgres
    - postfix
    - imagemagick
    - nodejs
    - yarn
    - { role: rvm.ruby, tags: ruby, rvm1_rubies: ['{{ ruby_version }}'], rvm1_user: 'deploy' }
    - nginx

  post_tasks:
    - name: Create gemset for {{ gemset }}
      command: bash -lc "rvm gemset create {{ gemset_name }}"
      become: yes
      become_user: deploy

    - name: populate /etc/environment
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}"
        line: "{{ item.key }}={{ item.value}}"
      with_items: "{{ env_vars }}"
