---
- name: "Yarn | GPG"
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: "Yarn | Ensure sources list file exists"
  file:
    path: /etc/apt/sources.list.d/yarn.list
    mode: 0644
    state: touch

- name: "Yarn | Ensure package is in sources list"
  lineinfile:
    dest: /etc/apt/sources.list.d/yarn.list
    regexp: 'deb http://dl.yarnpkg.com/debian/ stable main'
    line: 'deb http://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: Install Yarn
  apt:
    name: yarn
    state: latest