---
- name: Install node and NPM
  apt:
    name: [
      'nodejs',
      'npm'
    ]
      
- name: Configure the Yarn APT key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: Install Yarn
  apt:
    name: yarn