---

- name: Install PostgreSQL
  apt:
    name: [
    'postgresql',
    'postgresql-contrib',
    'libpq-dev',
    'python-psycopg2'
    ]


- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure database is created
  become_user: postgres
  postgresql_db:
    name: '{{ db_name }}'
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'

- name: Ensure user has access to the database
  become_user: postgres
  postgresql_user:
    db: '{{ db_name }}'
    name: '{{ db_user }}'
    password: '{{ db_password }}'
